module.exports = app => {
    const qtracker = require("./qtracker.controller.js");

    app.post("/qtracker/requestNWC", qtracker.requestNWC)
    app.post("/qtracker/requestNVN", qtracker.requestNVN)
    app.post("/qtracker/requestDIS", qtracker.requestDIS)
    app.post("/qtracker/requestPER", qtracker.requestPER)
    app.post("/qtracker/requestMOD", qtracker.requestMOD)
    app.post("/qtracker/requestDSO", qtracker.requestDSO)
    app.post("/qtracker/requestDOR", qtracker.requestDOR)
    app.post("/qtracker/requestCIT", qtracker.requestCIT)
    app.post("/qtracker/requestNRI", qtracker.requestNRI)
    app.post("/qtracker/requestNRB", qtracker.requestNRB)
    app.post("/qtracker/requestNRIDS", qtracker.requestNRIDS)
    app.post("/qtracker/requestRR", qtracker.requestRR)
    app.post("/qtracker/requestIS", qtracker.requestIS)
    app.post("/qtracker/uploadAttach", qtracker.uploadAttach)
    app.get("/qtracker/existsAttach/:incidence_number", qtracker.existsAttach)
    app.get("/qtracker/getAttach/:fileName", qtracker.getAttach)
    
    app.get("/qtracker/getNWC", qtracker.getNWC)
    app.get("/qtracker/getNVN", qtracker.getNVN)
    app.get("/qtracker/getDIS", qtracker.getDIS)
    app.get("/qtracker/getPER", qtracker.getPER)
    app.get("/qtracker/getMOD", qtracker.getMOD)
    app.get("/qtracker/getDSO", qtracker.getDSO)
    app.get("/qtracker/getDOR", qtracker.getDOR)
    app.get("/qtracker/getCIT", qtracker.getCIT)
    app.get("/qtracker/getNRI", qtracker.getNRI)
    app.get("/qtracker/getNRB", qtracker.getNRB)
    app.get("/qtracker/getNRIDS", qtracker.getNRIDS)
    app.get("/qtracker/getRP", qtracker.getRP)
    app.get("/qtracker/getIS", qtracker.getIS)

    app.get("/qtracker/getNWCByProjects/:email", qtracker.getNWCByProjects)
    app.get("/qtracker/getNVNByProjects/:email", qtracker.getNVNByProjects)
    app.get("/qtracker/getDISByProjects/:email", qtracker.getDISByProjects)
    app.get("/qtracker/getPERByProjects/:email", qtracker.getPERByProjects)
    app.get("/qtracker/getMODByProjects/:email", qtracker.getMODByProjects)
    app.get("/qtracker/getDSOByProjects/:email", qtracker.getDSOByProjects)
    app.get("/qtracker/getDORByProjects/:email", qtracker.getDORByProjects)
    app.get("/qtracker/getCITByProjects/:email", qtracker.getCITByProjects)
    app.get("/qtracker/getNRIByProjects/:email", qtracker.getNRIByProjects)
    app.get("/qtracker/getNRBByProjects/:email", qtracker.getNRBByProjects)
    app.get("/qtracker/getNRIDSByProjects/:email", qtracker.getNRIDSByProjects)
    app.get("/qtracker/getRPByProjects/:email", qtracker.getRPByProjects)
    app.get("/qtracker/getISByProjects/:email", qtracker.getISByProjects)

    app.post("/qtracker/updateStatus", qtracker.updateStatus)
    app.post("/qtracker/updateObservations", qtracker.updateObservations)
    app.post("/qtracker/updateHours", qtracker.updateHours)
    app.post("/qtracker/updatePriority", qtracker.updatePriority)

    app.get("/statusData", qtracker.statusData)
    app.get("/getProjects", qtracker.getProjects)
    app.post("/submitProjects", qtracker.submitProjects)

    app.get("/downloadGuideES", qtracker.downloadGuideES)
    app.get("/downloadGuideEN", qtracker.downloadGuideEN)
  };